### PR TITLE
Fix upsidedown printing

### PR DESCRIPTION
**Pull request by caternuson**
Fix for #19. Same as #22 but without addition of sideways.

upsidedown_test

### CODE REVIEW

**Review by ladyada — COMMENTED** [review]
do we want to have the firmware be a user-settable thing?

**Comment by caternuson** [comment]
maybe? want to move away from the simple `#define` approach currently being used? guess could still use that with preproc logic and have users add a `#define` before `#include`ing the lib header? but that seems klunky?

**Comment by ladyada** [comment]
that doesnt work, you cannot #define before an #include

**Comment by caternuson** [comment]
ah. so some new `setFirmware()` method? can it be queried from the printer? (not seeing anything)

**Comment by ladyada** [comment]
sure, setFirmware() or begin() arg - either!

**Comment by caternuson** [comment]
ok, will take look. should do that next to get the refactor in place.

**Comment by ladyada** [comment]
thanks! im trying to stay away from #defines, its too confusing for folks

**Pull request merged**
