### PR TITLE
Moved to actions, added a bunch of doxygen

### PR DESCRIPTION
**Pull request by dherrada**
@ladyada Should I be skipping the failing boards here?

### CODE REVIEW

**Comment by dherrada** [comment]
Theres also some really odd stuff going on with doxygen around #defines, but I'm not even sure if that will present itself in Actions

**Comment by ladyada** [comment]
please add test skip for adafruit_metro_m4

**Comment by dherrada** [comment]
Linking doxygen/doxygen#7858

**Comment by dherrada** [comment]
@ladyada Ok, I figured out the issue. Turns out I've got to add the documentation for #defines outside of the function.

**Comment by PaintYourDragon** [comment]
Looks good from here. Thank you! This is one of the most delicate Arduino libraries to work on and I’m grateful for your patience and diligence.

**Comment by PaintYourDragon** [comment]
Also, thanks for the Doxygen link in the README.md badge, didn’t know that was a thing. I’ll be adding it in any future Actions/clang/Doxy conversions I’m doing.

**Pull request merged**
